apiVersion: v1
kind: ConfigMap
metadata:
  name: element-web-config
  namespace: element
data:
  config.json: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": "https://synapse.test.duxigo.org",
          "server_name": "test.duxigo.org"
        },
        "m.identity_server": {
          "base_url": "https://vector.im"
        }
      },
      "default_server_name": "test.duxigo.org",
      "brand": "Element",
      "element_call": {
        "url": "https://call.test.duxigo.org"
      },
      "features": {
        "feature_new_spinner": true,
        "feature_pinning": true,
        "feature_custom_status": true
      },
      "default_federate": true,
      "default_theme": "light"
    }

